services:
  - type: web
    name: infravault-backend
    plan: free
    runtime: image
    image:
      url: maven:3.9-eclipse-temurin-21-alpine
    region: oregon
    rootDir: backend
    startCommand: "./mvnw spring-boot:run"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: infravault-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: infravault-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: infravault-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: infravault-db
    region: oregon
    plan: free
