services:
  - type: web
    name: infravault-backend
    runtime: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: infravault-db
          property: connectionString
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: infravault-db
    region: oregon
    plan: free
