services:
  - type: web
    name: infravault-backend
    region: oregon
    rootDir: backend
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: infravault-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: infravault-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: infravault-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: infravault-db
    region: oregon
    plan: free
