spring.application.name=backend

# PostgreSQL Database

spring.datasource.url=jdbc:postgresql://localhost:5432/password_manager?options=-c%20TimeZone%3DUTC
spring.datasource.username=password_admin
spring.datasource.password=change_me_dev_only

# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server

server.port=8080

# Actuator

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# AES-256 encryption key

app.encryption.key=PasswordManagerKey2026ABCD123456
